permalink: ':title'

markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               'naliwajek'
tagline:             ''
description:         'homepage of Jakub Naliwajek'
url:                 http://naliwajek.com
baseurl:             ''
